spring:
  application:
    name: barber-shop-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Fallback para dev se não for passado por env

jackson:
  time-zone: America/Sao_Paulo

server:
  port: 8084

